#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once dirname(__DIR__) ."/bootstrap.php";

$console = &$app["console"];

$console->add(new Command\SyncGeography());
$console->add(new Command\DownloadGeography());
$console->add(new Command\DownloadPackages());
$console->add(new Command\SyncHotels());
$console->add(new Command\SyncPackages());
$console->add(new Command\SyncPrices());
$console->add(new Command\PackageSearch());
$console->run();
